version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "58080:8080"
    volumes:
      - "./configs:/backend/configs"
      - "./uploads:/backend/uploads"

  rq_worker:
    build: 
      context: .
      dockerfile: ./docker/rq/Dockerfile
    volumes:
      - "./configs:/backend/configs"
    
  redis:
    image: "redis"
    ports:
      - "56379:6379"
      
  mongo:
    image: "mongo"
    ports:
      - "57017:27017"

  prometheus:
    image: "prom/prometheus"
    ports:
      - "57017:9090"
    volumes:
      - "./configs/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus:/prometheus"

networks:
  default:
    ipam:
      config:
        - subnet: 172.26.0.0/24