version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "58080:8080"
      - "58081:8081"
    volumes:
      - "./configs:/backend/configs"
      - "./uploads:/backend/uploads"
      - "./logging:/backend/logging"

  rq_worker:
    build: 
      context: .
      dockerfile: ./docker/rq/Dockerfile
    ports:
      - "58082:8082"
    volumes:
      - "./configs:/backend/configs"
      - "./mlruns:/backend/mlruns"
    
  redis:
    image: "redis"
    ports:
      - "56379:6379"
      
  mongo:
    image: "mongo"
    ports:
      - "57017:27017"

  prometheus:
    image: "prom/prometheus"
    ports:
      - "59090:9090"
    volumes:
      - "./configs/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus:/prometheus"

  alertmanager:
    image: "quay.io/prometheus/alertmanager"
    ports:
      - "59093:9093"
    volumes:
      - "./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml"

networks:
  default:
    ipam:
      config:
        - subnet: 172.26.0.0/24