apiVersion: v1
kind: PersistentVolume
metadata:
  name: automl-uploads-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/uploads