apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: automl
    tier: frontend
  name: automl-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: automl
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}