automl:
  available_models_classes:
    regression: [lgbm, catboost, ridge]
    classification: [lgbm, catboost, logreg]

storage:
  datasets: ./uploads/datasets
  models: ./uploads/models

rq:
  redis_host: 172.28.0.1
  redis_port: 56379

mongodb:
  mongo_host: 172.28.0.1
  mongo_port: 57017
  mongo_db_name: dev_database

telegram:
  api_key: YOUR_TOKEN_HERE

automl_api:
  api_host: 127.0.0.1
  api_port: 8080