global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'ml-project'

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['172.17.0.1:59093']

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:59090']
    
  - job_name: 'ml_api'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:8080']