name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Extract metadata (tags, labels) for rq Docker
      id: meta_rq
      uses: docker/metadata-action@v3.6.2
      with:
        images: bondani/automl_rq
        
    - name: Build and push rq Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        file: './docker/rq/Dockerfile'
        tags: ${{ steps.meta_rq.outputs.tags }}
        labels: ${{ steps.meta_rq.outputs.labels }}
        
    - name: Extract metadata (tags, labels) for api Docker
      id: meta_api
      uses: docker/metadata-action@v3.6.2
      with:
        images: bondani/automl_rq
        
    - name: Build and push api Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        file: './docker/api/Dockerfile'
        tags: ${{ steps.meta_api.outputs.tags }}
        labels: ${{ steps.meta_api.outputs.labels }}
        
    

