# This workflow will install Python dependencies and run tests

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run redis docker
      run: docker run --name some-redis -p 56379:6379 --rm -d redis

    - name: run mongo docker
      run: docker run --name some-mongo -p 57017:27017 --rm -d mongo

    - name: Test with pytest
      run: |
        pytest -s tests/
